version: '3.7'

services:
  nginx:
    build: ./services/nginx
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - ./services/web/:/usr/src/app/
    ports:
      - 5000
    env_file:
      - ./.env.dev
#  front:
#    image: mhuanteraxe/ded-script
#    container_name: front
#    ports:
#      - 5050